@bot.command()
async def server(ctx):
        role_count = len(ctx.guild.roles)
        emoji_count = len(ctx.guild.emojis)
        channel_count = len([x for x in ctx.guild.channels if type(x) == discord.channel.TextChannel])
        embed = discord.Embed(title=f"Server Information : {ctx.guild.name}", colour=0xf0000)  
        embed.add_field(name="Server Name:", value=f" ```{ctx.guild.name}```", inline=True)
        embed.add_field(name="Server ID:", value=f" ```{ctx.guild.id}```", inline=True)
        embed.add_field(name="Security Level:", value=f" ```{ctx.guild.verification_level}```", inline=False)
        embed.add_field(name="Creation Date:", value=f" ```{ctx.guild.created_at.__format__('%A, %d. %B %Y @ %H:%M:%S')}```", inline=False)
        embed.add_field(name="Total Categorys:", value=f" ```{len(ctx.guild.categories)}```", inline=True)
        embed.add_field(name="Text Channels:", value=f" ```{str(channel_count)}```", inline=True)
        embed.add_field(name="Voice Channels:", value=f" ```{len(ctx.guild.voice_channels)}```", inline=True)
        embed.add_field(name="Total Members:", value=f" ```{ctx.guild.member_count}```", inline=True)
        embed.add_field(name="Total Roles:", value=f' ```{str(role_count)}```', inline=True)
        embed.add_field(name="Total Emojis:", value=f' ```{str(emoji_count)}```', inline=True)
        embed.add_field(name="Total Boosts:", value=f' ```{str(ctx.guild.premium_subscription_count)}```', inline=True)
        embed.set_author(name="Lux - Github Proj")
        await ctx.send(embed=embed)  